#!/usr/bin/env python3
"""Generate the procedural sample meshes in assets/models/.

Units are meters, Y is up. Every mesh is written with positions, UVs and
normals (v/vt/vn faces). OBJ texture coordinates follow the OBJ convention:
v = 0 is the bottom of the image.

Run from the repo root:  python scripts/gen_sample_models.py
The output is deterministic, so re-running it produces identical files.
"""

import math
import os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "assets", "models")


class Mesh:
    def __init__(self, name):
        self.name = name
        self.v, self.vt, self.vn, self.faces = [], [], [], []

    def vert(self, p, uv, n):
        self.v.append(p)
        self.vt.append(uv)
        self.vn.append(n)
        return len(self.v)  # OBJ indices are 1-based

    def tri(self, a, b, c):
        self.faces.append((a, b, c))

    def quad(self, a, b, c, d):
        self.tri(a, b, c)
        self.tri(a, c, d)

    def write(self, filename, comment):
        path = os.path.join(OUT, filename)
        with open(path, "w", newline="\n") as f:
            f.write(f"# {comment}\n")
            f.write("# Generated by scripts/gen_sample_models.py. Public domain (CC0).\n")
            f.write(f"o {self.name}\n")
            for p in self.v:
                f.write("v {:.6f} {:.6f} {:.6f}\n".format(*p))
            for t in self.vt:
                f.write("vt {:.6f} {:.6f}\n".format(*t))
            for n in self.vn:
                f.write("vn {:.6f} {:.6f} {:.6f}\n".format(*n))
            for a, b, c in self.faces:
                f.write(f"f {a}/{a}/{a} {b}/{b}/{b} {c}/{c}/{c}\n")
        print(f"wrote {path}: {len(self.v)} vertices, {len(self.faces)} triangles")


def box(name, sx, sy, sz, y0=0.0):
    """Axis-aligned box centred on X/Z, bottom face at y0. Flat normals."""
    m = Mesh(name)
    hx, hz = sx * 0.5, sz * 0.5
    y1 = y0 + sy
    # (normal, four corners counter-clockwise seen from outside)
    faces = [
        ((0, 0, 1), [(-hx, y0, hz), (hx, y0, hz), (hx, y1, hz), (-hx, y1, hz)]),
        ((0, 0, -1), [(hx, y0, -hz), (-hx, y0, -hz), (-hx, y1, -hz), (hx, y1, -hz)]),
        ((1, 0, 0), [(hx, y0, hz), (hx, y0, -hz), (hx, y1, -hz), (hx, y1, hz)]),
        ((-1, 0, 0), [(-hx, y0, -hz), (-hx, y0, hz), (-hx, y1, hz), (-hx, y1, -hz)]),
        ((0, 1, 0), [(-hx, y1, hz), (hx, y1, hz), (hx, y1, -hz), (-hx, y1, -hz)]),
        ((0, -1, 0), [(-hx, y0, -hz), (hx, y0, -hz), (hx, y0, hz), (-hx, y0, hz)]),
    ]
    uvs = [(0, 0), (1, 0), (1, 1), (0, 1)]
    for n, corners in faces:
        idx = [m.vert(p, uv, n) for p, uv in zip(corners, uvs)]
        m.quad(*idx)
    return m


def uv_sphere(name, radius, rings, segments):
    """UV sphere centred at the origin. Smooth normals, seam duplicated for UVs."""
    m = Mesh(name)
    grid = []
    for r in range(rings + 1):
        theta = math.pi * r / rings  # 0 at +Y
        row = []
        for s in range(segments + 1):
            phi = 2.0 * math.pi * s / segments
            n = (math.sin(theta) * math.cos(phi), math.cos(theta), -math.sin(theta) * math.sin(phi))
            p = tuple(radius * c for c in n)
            row.append(m.vert(p, (s / segments, 1.0 - r / rings), n))
        grid.append(row)
    for r in range(rings):
        for s in range(segments):
            a, b = grid[r][s], grid[r + 1][s]
            c, d = grid[r + 1][s + 1], grid[r][s + 1]
            if r == 0:
                m.tri(a, b, c)
            elif r == rings - 1:
                m.tri(a, b, d)
            else:
                m.quad(a, b, c, d)
    return m


def pedestal(name, radius, height, bevel, segments):
    """Round product stand: a cylinder with a small 45-degree chamfer on the top edge."""
    m = Mesh(name)
    top = height
    shoulder = height - bevel
    inner = radius - bevel

    def ring(y, r, n_of):
        out = []
        for s in range(segments + 1):
            phi = 2.0 * math.pi * s / segments
            c, sn = math.cos(phi), -math.sin(phi)
            out.append(m.vert((r * c, y, r * sn), (s / segments, y / height), n_of(c, sn)))
        return out

    side = lambda c, s: (c, 0.0, s)
    k = 1.0 / math.sqrt(2.0)
    cham = lambda c, s: (c * k, k, s * k)

    bottom_side = ring(0.0, radius, side)
    upper_side = ring(shoulder, radius, side)
    for s in range(segments):
        m.quad(bottom_side[s], bottom_side[s + 1], upper_side[s + 1], upper_side[s])

    lower_cham = ring(shoulder, radius, cham)
    upper_cham = ring(top, inner, cham)
    for s in range(segments):
        m.quad(lower_cham[s], lower_cham[s + 1], upper_cham[s + 1], upper_cham[s])

    def cap(y, r, up):
        n = (0.0, 1.0 if up else -1.0, 0.0)
        centre = m.vert((0.0, y, 0.0), (0.5, 0.5), n)
        rim = []
        for s in range(segments):
            phi = 2.0 * math.pi * s / segments
            c, sn = math.cos(phi), -math.sin(phi)
            rim.append(m.vert((r * c, y, r * sn), (0.5 + 0.5 * c, 0.5 - 0.5 * sn), n))
        for s in range(segments):
            a, b = rim[s], rim[(s + 1) % segments]
            if up:
                m.tri(centre, a, b)
            else:
                m.tri(centre, b, a)

    cap(top, inner, True)
    cap(0.0, radius, False)
    return m


def floor(name, size):
    m = Mesh(name)
    h = size * 0.5
    n = (0.0, 1.0, 0.0)
    tile = size / 2.0  # one texture repeat every 2 m
    a = m.vert((-h, 0.0, h), (0.0, 0.0), n)
    b = m.vert((h, 0.0, h), (tile, 0.0), n)
    c = m.vert((h, 0.0, -h), (tile, tile), n)
    d = m.vert((-h, 0.0, -h), (0.0, tile), n)
    m.quad(a, b, c, d)
    return m


def main():
    os.makedirs(OUT, exist_ok=True)
    box("cube", 1.0, 1.0, 1.0).write("cube.obj", "Unit product cube, 1 x 1 x 1 m, bottom on y = 0.")
    uv_sphere("sphere", 0.5, 32, 64).write("sphere.obj", "UV sphere, radius 0.5 m, centred at the origin.")
    pedestal("product_stand", 0.6, 0.45, 0.02, 96).write(
        "product_stand.obj", "Round pedestal, radius 0.6 m, top at y = 0.45 m.")
    floor("floor", 12.0).write("floor.obj", "Ground plane, 12 x 12 m at y = 0.")


if __name__ == "__main__":
    main()
